### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by KELiON** [nylas/N1-Markdown-Composer#9]
When I try to install this plugin I see this error:

<img width="532" alt="captura de pantalla 2016-03-17 a las 13 42 33" src="https://cloud.githubusercontent.com/assets/594298/13842152/20bb5cb2-ec46-11e5-94c8-0f5ad97d069e.png">

But I see disabled plugin in plugins list. When I try to enable it with opened developer tools I see this in console:

https://gist.github.com/KELiON/6adcfba37b1a91ecc96b

OsX 10.11.1
Nylas N1 0.4.14-53cd69b

**Comment by 1vank1n** [comment]
Same error. @KELiON, did you find desicion?

**Comment by joelostblom** [comment]
Same error, the folder is added to `./nylas/packages`, but the plugin fails to install. This is on Linux (kernel 4.4.5-1) with Nylas 0.4.14-53cd69b.

**Comment by 1vank1n** [comment]
I found the answer. You need to install Atom.

**Comment by KELiON** [comment]
@1vank1n it is installed on my machine

**Comment by 1vank1n** [comment]
@KELiON, strangely... after install Atom and relaunch Nylas problem was solved.

**Comment by angusfretwell** [comment]
I have Atom installed (not sure why this is a requirement), and am also experiencing this issue.

**Comment by angusfretwell** [comment]
Running `apm install` from the plugin directory manually (`~/.nylas/packages/N1-Markdown-Composer`) works fine; after that the plugin functions as expected.

**Comment by KELiON** [comment]
@angusfretwell thanks, it works for me! But now something is broken in styles :( 
![captura de pantalla 2016-03-23 a las 10 10 07](https://cloud.githubusercontent.com/assets/594298/13977174/3254cbcc-f0e0-11e5-980d-2b90953fcd3f.png)

**Comment by angusfretwell** [comment]
@KELiON Make sure the plugin directory is called exactly `N1-Markdown-Composer` (i.e. not `N1-Markdown-Composer-master` if you downloaded it as a zip from GitHub), and then restart the app.

**Comment by KELiON** [comment]
Finally! ![captura de pantalla 2016-03-23 a las 10 25 34](https://cloud.githubusercontent.com/assets/594298/13977342/9ad947da-f0e1-11e5-9c28-f79566a1f4d8.png)

**Comment by angusfretwell** [comment]
Woohoo!

I think you should re-open this ticket, as I think the failed `apm install` you initially reported is a bug (maybe it's a problem with Nylas rather than this plugin), and it should be investigated.

**Comment by devonzuegel** [comment]
I had the same issues. Renaming the directory from `N1-Markdown-Composer-master` to `N1-Markdown-Composer` _and_ running `apm` directly in the directory worked for me.

**Comment by angusfretwell** [comment]
I have a suspicion that the directory being named `N1-Markdown-Composer-master` might have caused the initial `apm install` issue.

**Comment by KELiON** [comment]
@angusfretwell nope, I just tried to uninstall, and install from `N1-Markdown-Composer` folder and it is failded

**Comment by 1vank1n** [comment]
I just installed. Short instruction:
1. Download zip
2. Unpack
3. Rename folder to `N1-Markdown-Composer`
4. Move unpacked folder to `~/.nylas/packages/`
5. Check that Nylas app closed
6. In terminal `cd ~/.nylas/packages/N1-Markdown-Composer`
7. `apm install`
8. wait... Done!

**Comment by jstejada** [comment]
Hi all, indeed the installation problem is due to the fact that `apm` does not currently support installing dependencies from Github https://github.com/atom/apm/issues/355

The instructions provided by @1vank1n should be good as a workaround, I'm going to update the readme to include them.

Thanks! and sorry for the trouble

**Comment by jcreamer898** [comment]
After following the steps above, when I re-opened Nylas, I was unable to type a message at all...

![](http://d.pr/i/17WuL+)

**Comment by plainclothes** [comment]
I'm getting the same problem. When I install the package manually from console, it appears to succeed. When I launch N1, the plug-in is disabled. At that point, composing works as expected. Once I enable Markdown, the message area in the composer is just gone. Tabbing from the 'subject' field just cycles back to the recips. There is no message field.

**Comment by fobbyal** [comment]
Is this suppose to work for windows? I am having similar problems. Although i suspect it might be a apm issue. The dependency modules are stil installed in deeply nested folders that are not supported under the windows operating system (path too long). NPM fixed this issue after version 3. I am not sure if there is a updated apm that does things differently.

**Comment by jstejada** [comment]
Hi everyone, I've updated the plugin in https://github.com/nylas/N1-Markdown-Composer/commit/48841527ba7fbfabcac6ce8d20f067df7ead594c to work correclty with the latest N1 version. Let me know if you're still running into issues

cc @jcreamer898

**Comment by jcreamer898** [comment]
So, now the editor works, however, no markdown plugin loads probably because of...

![](http://d.pr/i/1lRUY+)

**Comment by devonzuegel** [comment]
I made some progress by running:

``` bash
$ npm install underscore -d
// output
$ npm install react -d
// output
$ npm install react-dom -d
// output
```

Then I checked and unchecked the plugin toggle in Preferences/Plugins/Installed Plugins.

I'm no longer receiving those "Failed to activate *" messages, but now I'm getting:

![image](https://cloud.githubusercontent.com/assets/6979755/15057948/57782dd0-12ce-11e6-92e6-0b2b11172d16.png)

**Comment by MagisDing** [comment]
Followed the detailed instructions by @1vank1n ,still not working. I got the prompt"installing modules successful" after running "apm install", but couldn't got the markdown interface.
OS: mac OS 10.11.4
Nylas: Version 0.4.33-e8f137e (0.4.33-e8f137e)

**Comment by youlu-cn** [comment]
@devonzuegel is it working right now? Seems that I have the same issue with you.

**Comment by devonzuegel** [comment]
@youlu-cn Nope, I unfortunately couldn't get it to work.

**Comment by andrew-zyf** [comment]
I followed the approach of  @1vank1n , it showed "Installing modules done", but there's no markdown in mail window at all. I hope more update on it.
Thanks guys!

OS: Windows 10

**Comment by savior1980** [comment]
I am in the same point as @devonzuegel tried install underscore and react but finally the plugin fails to load in composer window. OS: Mac OS X 10.11.5 Nylas: Versión 0.4.40-85cf726 (0.4.40-85cf726)

![nylas1](https://cloud.githubusercontent.com/assets/1453299/15701505/e6422928-27da-11e6-81a8-070e8034bda8.png)
![nylas2](https://cloud.githubusercontent.com/assets/1453299/15701526/04afedfa-27db-11e6-9cb4-f2bdf6091e1c.png)

And 7 more exceptions similar to the ones already reported in this thread

**Comment by jstejada** [comment]
hi all! I've pushed an update that should resolve all dependency issues and work correctly with the latest N1 version. More details here: https://github.com/nylas/N1-Markdown-Composer/commit/6a0d325d89c86c4710bd97b4dff1084a81bc5c7e

Let me know if you continue having issues. Thanks for your patience! cc @devonzuegel , @jcreamer898, @savior1980, @MagisDing , @youlu-cn, @yuphone
